using UnityEngine;
using UnityEngine.Tilemaps;

public class RoomToOutside : MonoBehaviour
{
    public Transform player;            // ğŸ§ í”Œë ˆì´ì–´
    public Transform destinationPoint;  // ğŸ“ ë„ë‹¬í•´ì•¼ í•˜ëŠ” ìœ„ì¹˜
    public Transform targetPoint;       // ğŸ¯ ì´ë™í•  ìœ„ì¹˜
    public Tilemap nextTilemap;         // ğŸ—ºï¸ ë„ì°©í•œ ë°©ì˜ íƒ€ì¼ë§µ

    public float triggerRadius = 0.2f;  // ë„ë‹¬ íŒì • ê±°ë¦¬ ë°˜ì§€ë¦„
    public float cooldown = 1f;         // ë°˜ë³µ ì´ë™ ë°©ì§€ ì¿¨íƒ€ì„

    private FollowCamera camFollow;
    private float lastTeleportTime = -10f;

    public bool isAnim = false;
    public float animTime = 1f;
    float currentAnimTime = 0f;

    public string animName;

    public float animMoveSpeed = 1f;

    bool animTeleport = false;

    PlayerMovement playerMovement;

    void Start()
    {
        camFollow = Camera.main.GetComponent<FollowCamera>();
        player = InventoryManager.FindFirstObjectByType<InventoryManager>().player.transform;
        playerMovement = player.GetComponent<PlayerMovement>();

        currentAnimTime = animTime;
    }

    void Update()
    {
        if (player == null || destinationPoint == null || targetPoint == null || camFollow == null) return;

        float distance = Vector2.Distance(player.position, destinationPoint.position);

        if (distance <= triggerRadius && Time.time - lastTeleportTime >= cooldown)
        {
            if (!isAnim)
            {
                Debug.Log("âœ… ìë™ ì´ë™ íŠ¸ë¦¬ê±° ë°œë™!");
                player.position = targetPoint.position;
                camFollow.SetNewTilemap(nextTilemap);
                lastTeleportTime = Time.time;
            }
            else
            {
                animTeleport = true;

                playerMovement.canMove = false;
                playerMovement.target = this.gameObject;
            }
        }

        if (animTeleport)
        {
            if (playerMovement.goal)
            {
                playerMovement.CallAnimation(animName, animMoveSpeed);

                playerMovement.target = null;

                currentAnimTime -= Time.deltaTime;
                if (currentAnimTime <= 0f)
                {
                    player.position = targetPoint.position;
                    camFollow.SetNewTilemap(nextTilemap);
                    lastTeleportTime = Time.time;

                    playerMovement.canMove = true;

                    playerMovement.RetunAnimation();

                    animTeleport = false;
                    currentAnimTime = animTime;
                }
            }
        }
    }
}